<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClaudeStack.API\ClaudeStack.API.csproj" />
  </ItemGroup>

</Project>
