<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\autolist\**" />
    <Content Remove="wwwroot\lib\autolist\**" />
    <EmbeddedResource Remove="wwwroot\lib\autolist\**" />
    <None Remove="wwwroot\lib\autolist\**" />
  </ItemGroup>

</Project>
