<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Magick.NET-Q8-x64" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Photos\policy.xml" LogicalName="GazetaMarketplace.Infrastructure.Photos.policy.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GazetaMarketplace.Core\GazetaMarketplace.Core.csproj" />
  </ItemGroup>

</Project>
