// <auto-generated />
using System;
using GazetaMarketplace.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GazetaMarketplace.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003170615_AssignFieldGroupsToRealEstateServicesAndJobs")]
    partial class AssignFieldGroupsToRealEstateServicesAndJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GazetaMarketplace.Core.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldGroup")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_Name_Root")
                        .HasFilter("[ParentId] IS NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_Slug");

                    b.HasIndex("ParentId", "DisplayOrder")
                        .HasDatabaseName("IX_Categories_ParentId_DisplayOrder");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_ParentId_Name")
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_NotOwnParent", "[ParentId] IS NULL OR [ParentId] <> [Id]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Imóveis",
                            Slug = "imoveis"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Automóveis, Peças e Acessórios",
                            Slug = "automoveis-pecas-e-acessorios"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Autopeças",
                            ParentId = 2,
                            Slug = "autopecas"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Celulares e Telefonia",
                            Slug = "celulares-e-telefonia"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Casa, Decoração e Utensílios",
                            Slug = "casa-decoracao-e-utensilios"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Esportes e Fitness",
                            Slug = "esportes-e-fitness"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Serviços",
                            Slug = "servicos-grupo"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Moda e beleza",
                            Slug = "moda-e-beleza"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Artigos infantis",
                            Slug = "artigos-infantis"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Animais de estimação",
                            Slug = "animais-de-estimacao"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Música e hobbies",
                            Slug = "musica-e-hobbies"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Agro e indústria",
                            Slug = "agro-e-industria"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 12,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Vagas de emprego",
                            Slug = "vagas-de-emprego-grupo"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 13,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Comércio",
                            Slug = "comercio"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 14,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Câmeras e Drones",
                            Slug = "cameras-e-drones"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 15,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Games",
                            Slug = "games"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 16,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "TVs e video",
                            Slug = "tvs-e-video"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 17,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Áudio",
                            Slug = "audio"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 18,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Informática",
                            Slug = "informatica"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 19,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Eletro",
                            Slug = "eletro"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 20,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Móveis",
                            Slug = "moveis"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 21,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Materiais de Construção",
                            Slug = "materiais-de-construcao"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 22,
                            IsPostable = false,
                            IsSystem = true,
                            Name = "Escritório e Home Office",
                            Slug = "escritorio-e-home-office"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            FieldGroup = "RealEstate",
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Apartamentos",
                            ParentId = 1,
                            Slug = "apartamentos"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            FieldGroup = "RealEstate",
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Casas",
                            ParentId = 1,
                            Slug = "casas"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Aluguel de quartos",
                            ParentId = 1,
                            Slug = "aluguel-de-quartos"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Temporada",
                            ParentId = 1,
                            Slug = "temporada"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            FieldGroup = "RealEstate",
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Terrenos, sítios e fazendas",
                            ParentId = 1,
                            Slug = "terrenos-sitios-e-fazendas"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            FieldGroup = "RealEstate",
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Comércio e indústria",
                            ParentId = 1,
                            Slug = "comercio-e-industria"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Carros, vans e utilitários",
                            ParentId = 2,
                            Slug = "cars"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Caminhões",
                            ParentId = 2,
                            Slug = "caminhoes"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Ônibus",
                            ParentId = 2,
                            Slug = "onibus"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Motos",
                            ParentId = 2,
                            Slug = "motos"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Barcos e aeronaves",
                            ParentId = 2,
                            Slug = "barcos-e-aeronaves"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças para carros, vans e utilitários",
                            ParentId = 3,
                            Slug = "pecas-carros-vans-e-utilitarios"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças para caminhões",
                            ParentId = 3,
                            Slug = "pecas-caminhoes"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças para motos",
                            ParentId = 3,
                            Slug = "pecas-motos"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças para barcos e aeronaves",
                            ParentId = 3,
                            Slug = "pecas-barcos-e-aeronaves"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças para ônibus",
                            ParentId = 3,
                            Slug = "pecas-onibus"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Celulares e Smartphones",
                            ParentId = 4,
                            Slug = "celulares-e-smartphones"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Acessórios de Celular",
                            ParentId = 4,
                            Slug = "acessorios-de-celular"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças de Celular",
                            ParentId = 4,
                            Slug = "pecas-de-celular"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Smartwatches",
                            ParentId = 4,
                            Slug = "smartwatches"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Acessórios Para Smartwatch",
                            ParentId = 4,
                            Slug = "acessorios-para-smartwatch"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Telefonia Fixa e Sem Fio",
                            ParentId = 4,
                            Slug = "telefonia-fixa-e-sem-fio"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Tecidos de Cama, Mesa e Banho",
                            ParentId = 5,
                            Slug = "tecidos-de-cama-mesa-e-banho"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Decorações Para Casa",
                            ParentId = 5,
                            Slug = "decoracoes-para-casa"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Casa Inteligente",
                            ParentId = 5,
                            Slug = "casa-inteligente"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Utensílios Para Cozinha",
                            ParentId = 5,
                            Slug = "utensilios-para-cozinha"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Utensílios Para Banheiro e Limpeza",
                            ParentId = 5,
                            Slug = "utensilios-para-banheiro-e-limpeza"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Iluminação",
                            ParentId = 5,
                            Slug = "iluminacao"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Segurança Residencial",
                            ParentId = 5,
                            Slug = "seguranca-residencial"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Jardinagem e Plantas",
                            ParentId = 5,
                            Slug = "jardinagem-e-plantas"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Área Externa",
                            ParentId = 5,
                            Slug = "area-externa"
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Ciclismo",
                            ParentId = 6,
                            Slug = "ciclismo"
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Academia e Exercícios",
                            ParentId = 6,
                            Slug = "academia-e-exercicios"
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Acampamento",
                            ParentId = 6,
                            Slug = "acampamento"
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Esportes Sobre Rodas",
                            ParentId = 6,
                            Slug = "esportes-sobre-rodas"
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Esportes de Quadra e Ao Ar Livre",
                            ParentId = 6,
                            Slug = "esportes-de-quadra-e-ao-ar-livre"
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Esportes Aquáticos",
                            ParentId = 6,
                            Slug = "esportes-aquaticos"
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Roupas Esportivas",
                            ParentId = 6,
                            Slug = "roupas-esportivas"
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Calçados Esportivos",
                            ParentId = 6,
                            Slug = "calcados-esportivos"
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            FieldGroup = "Services",
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Serviços",
                            ParentId = 7,
                            Slug = "servicos"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Beleza e Cuidados Pessoais",
                            ParentId = 8,
                            Slug = "beleza-e-cuidados-pessoais"
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Roupas",
                            ParentId = 8,
                            Slug = "roupas"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Calçados",
                            ParentId = 8,
                            Slug = "calcados"
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Bolsas, malas e mochilas",
                            ParentId = 8,
                            Slug = "bolsas-malas-e-mochilas"
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Acessórios",
                            ParentId = 8,
                            Slug = "acessorios"
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Roupas Infantis",
                            ParentId = 9,
                            Slug = "roupas-infantis"
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Brinquedos e Jogos",
                            ParentId = 9,
                            Slug = "brinquedos-e-jogos"
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Maternidade e Cuidados com o Bebê",
                            ParentId = 9,
                            Slug = "maternidade-e-cuidados-com-o-bebe"
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Calçados Infantis",
                            ParentId = 9,
                            Slug = "calcados-infantis"
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Roupas para Bebês",
                            ParentId = 9,
                            Slug = "roupas-para-bebes"
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Calçados Para Bebês",
                            ParentId = 9,
                            Slug = "calcados-para-bebes"
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Móveis Infantis",
                            ParentId = 9,
                            Slug = "moveis-infantis"
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Acessórios para pets",
                            ParentId = 10,
                            Slug = "acessorios-para-pets"
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Instrumentos musicais",
                            ParentId = 11,
                            Slug = "instrumentos-musicais"
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "CDs, DVDs etc",
                            ParentId = 11,
                            Slug = "cds-dvds-etc"
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Livros e revistas",
                            ParentId = 11,
                            Slug = "livros-e-revistas"
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Antiguidades",
                            ParentId = 11,
                            Slug = "antiguidades"
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Hobbies e coleções",
                            ParentId = 11,
                            Slug = "hobbies-e-colecoes"
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Tratores e máquinas agrícolas",
                            ParentId = 12,
                            Slug = "tratores-e-maquinas-agricolas"
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças para tratores e máquinas",
                            ParentId = 12,
                            Slug = "pecas-para-tratores-e-maquinas"
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Máquinas pesadas para construção",
                            ParentId = 12,
                            Slug = "maquinas-pesadas-para-construcao"
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Máquinas para produção industrial",
                            ParentId = 12,
                            Slug = "maquinas-para-producao-industrial"
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Outros itens para agro e indústria",
                            ParentId = 12,
                            Slug = "outros-itens-para-agro-e-industria"
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Produção Rural",
                            ParentId = 12,
                            Slug = "producao-rural"
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            FieldGroup = "Jobs",
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Vagas de emprego",
                            ParentId = 13,
                            Slug = "vagas-de-emprego"
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Trailers e carrinhos comerciais",
                            ParentId = 14,
                            Slug = "trailers-e-carrinhos-comerciais"
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Equipamentos Para Comércio",
                            ParentId = 14,
                            Slug = "equipamentos-para-comercio"
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Gastronomia e Hotelaria",
                            ParentId = 14,
                            Slug = "gastronomia-e-hotelaria"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Equipamentos Médicos e Hospitalares",
                            ParentId = 14,
                            Slug = "equipamentos-medicos-e-hospitalares"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Uniformes de Trabalho e EPIs",
                            ParentId = 14,
                            Slug = "uniformes-de-trabalho-e-epis"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Câmeras e Filmadoras",
                            ParentId = 15,
                            Slug = "cameras-e-filmadoras"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Acessórios para Câmeras e Filmadoras",
                            ParentId = 15,
                            Slug = "acessorios-para-cameras-e-filmadoras"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Drones",
                            ParentId = 15,
                            Slug = "drones"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Consoles de Vídeo Game",
                            ParentId = 16,
                            Slug = "consoles-de-video-game"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Jogos de Vídeo Game",
                            ParentId = 16,
                            Slug = "jogos-de-video-game"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças e Acessórios de Vídeo Game",
                            ParentId = 16,
                            Slug = "pecas-e-acessorios-de-video-game"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "TVs",
                            ParentId = 17,
                            Slug = "tvs"
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças e Acessórios para TV",
                            ParentId = 17,
                            Slug = "pecas-e-acessorios-para-tv"
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Projetores e Telas de Projeção",
                            ParentId = 17,
                            Slug = "projetores-e-telas-de-projecao"
                        },
                        new
                        {
                            Id = 111,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "DVD, Blu-Ray e Vídeo Cassete",
                            ParentId = 17,
                            Slug = "dvd-blu-ray-e-video-cassete"
                        },
                        new
                        {
                            Id = 112,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Dispositivos de Streaming",
                            ParentId = 17,
                            Slug = "dispositivos-de-streaming"
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Fones de Ouvido",
                            ParentId = 18,
                            Slug = "fones-de-ouvido"
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Aparelhos de Som",
                            ParentId = 18,
                            Slug = "aparelhos-de-som"
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Microfones e Gravadores",
                            ParentId = 18,
                            Slug = "microfones-e-gravadores"
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Equipamentos e Acessórios de Som",
                            ParentId = 18,
                            Slug = "equipamentos-e-acessorios-de-som"
                        },
                        new
                        {
                            Id = 117,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Computadores e Desktops",
                            ParentId = 19,
                            Slug = "computadores-e-desktops"
                        },
                        new
                        {
                            Id = 118,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Notebooks",
                            ParentId = 19,
                            Slug = "notebooks"
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Monitores",
                            ParentId = 19,
                            Slug = "monitores"
                        },
                        new
                        {
                            Id = 120,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Periféricos e Acessórios de Computador",
                            ParentId = 19,
                            Slug = "perifericos-e-acessorios-de-computador"
                        },
                        new
                        {
                            Id = 121,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Peças de Hardware",
                            ParentId = 19,
                            Slug = "pecas-de-hardware"
                        },
                        new
                        {
                            Id = 122,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Armazenamento",
                            ParentId = 19,
                            Slug = "armazenamento"
                        },
                        new
                        {
                            Id = 123,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Memória RAM",
                            ParentId = 19,
                            Slug = "memoria-ram"
                        },
                        new
                        {
                            Id = 124,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Processadores",
                            ParentId = 19,
                            Slug = "processadores"
                        },
                        new
                        {
                            Id = 125,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Placas de Vídeo",
                            ParentId = 19,
                            Slug = "placas-de-video"
                        },
                        new
                        {
                            Id = 126,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Conectividade e Dispositivos de Rede",
                            ParentId = 19,
                            Slug = "conectividade-e-dispositivos-de-rede"
                        },
                        new
                        {
                            Id = 127,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Tablets e E-Readers",
                            ParentId = 19,
                            Slug = "tablets-e-e-readers"
                        },
                        new
                        {
                            Id = 128,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Ar-condicionados",
                            ParentId = 20,
                            Slug = "ar-condicionados"
                        },
                        new
                        {
                            Id = 129,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Ventiladores e Climatizadores",
                            ParentId = 20,
                            Slug = "ventiladores-e-climatizadores"
                        },
                        new
                        {
                            Id = 130,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Geladeiras e Freezers",
                            ParentId = 20,
                            Slug = "geladeiras-e-freezers"
                        },
                        new
                        {
                            Id = 131,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Fogões e Fornos",
                            ParentId = 20,
                            Slug = "fogoes-e-fornos"
                        },
                        new
                        {
                            Id = 132,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Máquinas de Lavar e Secadoras",
                            ParentId = 20,
                            Slug = "maquinas-de-lavar-e-secadoras"
                        },
                        new
                        {
                            Id = 133,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Eletroportáteis Para Cozinha e Limpeza",
                            ParentId = 20,
                            Slug = "eletroportateis-para-cozinha-e-limpeza"
                        },
                        new
                        {
                            Id = 134,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Eletroportáteis Para Cuidados Pessoais",
                            ParentId = 20,
                            Slug = "eletroportateis-para-cuidados-pessoais"
                        },
                        new
                        {
                            Id = 135,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Camas e Colchões",
                            ParentId = 21,
                            Slug = "camas-e-colchoes"
                        },
                        new
                        {
                            Id = 136,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Sofás e Poltronas",
                            ParentId = 21,
                            Slug = "sofas-e-poltronas"
                        },
                        new
                        {
                            Id = 137,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Bancos e Cadeiras",
                            ParentId = 21,
                            Slug = "bancos-e-cadeiras"
                        },
                        new
                        {
                            Id = 138,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Mesas",
                            ParentId = 21,
                            Slug = "mesas"
                        },
                        new
                        {
                            Id = 139,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Escrivaninhas e Penteadeiras",
                            ParentId = 21,
                            Slug = "escrivaninhas-e-penteadeiras"
                        },
                        new
                        {
                            Id = 140,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Racks e Painéis",
                            ParentId = 21,
                            Slug = "racks-e-paineis"
                        },
                        new
                        {
                            Id = 141,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Armários e Guarda-Roupas",
                            ParentId = 21,
                            Slug = "armarios-e-guarda-roupas"
                        },
                        new
                        {
                            Id = 142,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Móveis Para Organização",
                            ParentId = 21,
                            Slug = "moveis-para-organizacao"
                        },
                        new
                        {
                            Id = 143,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Fundação e Estrutura",
                            ParentId = 22,
                            Slug = "fundacao-e-estrutura"
                        },
                        new
                        {
                            Id = 144,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Alvenaria",
                            ParentId = 22,
                            Slug = "alvenaria"
                        },
                        new
                        {
                            Id = 145,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Pisos e Revestimentos",
                            ParentId = 22,
                            Slug = "pisos-e-revestimentos"
                        },
                        new
                        {
                            Id = 146,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Portas e Janelas",
                            ParentId = 22,
                            Slug = "portas-e-janelas"
                        },
                        new
                        {
                            Id = 147,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Cubas e Pias",
                            ParentId = 22,
                            Slug = "cubas-e-pias"
                        },
                        new
                        {
                            Id = 148,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Torneiras, Duchas e Vasos",
                            ParentId = 22,
                            Slug = "torneiras-duchas-e-vasos"
                        },
                        new
                        {
                            Id = 149,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Instalações Elétricas e Hidráulicas",
                            ParentId = 22,
                            Slug = "instalacoes-eletricas-e-hidraulicas"
                        },
                        new
                        {
                            Id = 150,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Ferramentas de Construção",
                            ParentId = 22,
                            Slug = "ferramentas-de-construcao"
                        },
                        new
                        {
                            Id = 151,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Ferramentas de Pintura",
                            ParentId = 22,
                            Slug = "ferramentas-de-pintura"
                        },
                        new
                        {
                            Id = 152,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Itens Para Escritório",
                            ParentId = 23,
                            Slug = "itens-para-escritorio"
                        },
                        new
                        {
                            Id = 153,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Cadeiras de Escritório e Gamer",
                            ParentId = 23,
                            Slug = "cadeiras-de-escritorio-e-gamer"
                        },
                        new
                        {
                            Id = 154,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Móveis de Escritório",
                            ParentId = 23,
                            Slug = "moveis-de-escritorio"
                        },
                        new
                        {
                            Id = 155,
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsPostable = true,
                            IsSystem = true,
                            Name = "Papelaria",
                            ParentId = 23,
                            Slug = "papelaria"
                        });
                });

            modelBuilder.Entity("GazetaMarketplace.Core.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_AuditEntries_OccurredAt");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("IX_AuditEntries_ActorId_OccurredAt");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_AuditEntries_TargetType_TargetId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("GazetaMarketplace.Core.Entities.PasswordRecoveryAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_PasswordRecoveryAttempts_RequestedAt");

                    b.HasIndex("Email", "RequestedAt")
                        .HasDatabaseName("IX_PasswordRecoveryAttempts_Email_RequestedAt");

                    b.HasIndex("Ip", "RequestedAt")
                        .HasDatabaseName("IX_PasswordRecoveryAttempts_Ip_RequestedAt");

                    b.ToTable("PasswordRecoveryAttempts", (string)null);
                });

            modelBuilder.Entity("GazetaMarketplace.Infrastructure.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "5c0b1d2a-8f7e-4a39-9d41-0a1e6c3b7f01",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "9e4a6f3c-2b15-4d87-a6c0-7d2f8e1b5a02",
                            Name = "Redator",
                            NormalizedName = "REDATOR"
                        });
                });

            modelBuilder.Entity("GazetaMarketplace.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GazetaMarketplace.Core.Categories.Category", b =>
                {
                    b.HasOne("GazetaMarketplace.Core.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GazetaMarketplace.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GazetaMarketplace.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GazetaMarketplace.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GazetaMarketplace.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GazetaMarketplace.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GazetaMarketplace.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
